// Versioned local notices. Native Health/GPS permissions are separate choices.
export const LEGAL_VERSION = '2026-10-08';
export const legalKey = userId => `korva:legal:${userId}`;
export const onboardingKey = userId => `korva:onboarding:${userId}`;
export const TERMINOS = [
  ['Sobre Korva', 'Korva Aventuras es una marca operada por Korva Adventures LLC. La app permite registrar actividad, seguir desafíos virtuales y explorar sus historias y mapas. Estos términos regulan el uso de la app; las condiciones de cada compra se informan en la tienda.'],
  ['Desafíos gratuitos y pagos', 'Las rutas gratuitas requieren que confirmes tu participación y no incluyen una medalla física. Una eventual compra será opcional y tendrá sus propias condiciones. Los desafíos pagos incluyen lo indicado en su ficha y pedido. Crear una cuenta no realiza ninguna compra.'],
  ['Tu progreso y tus pausas', 'Podés registrar actividades con GPS o manualmente y conectar Strava de forma opcional. Una actividad elegible puede sumar a varios desafíos activos. Cada desafío respeta su fecha de inicio, versión y períodos de pausa. No cargues una misma actividad varias veces. Los kilómetros y los mapas son representaciones de tu avance, no instrucciones de navegación.'],
  ['Salud es opcional', 'Conectar Apple Salud o Health Connect permite consultar tu movimiento diario. Para que la distancia aporte a un desafío tenés que elegirlo y confirmar por separado. Empieza desde el día siguiente a la confirmación y respeta las pausas. Los pasos no se convierten a kilómetros y se evita repetir distancia ya registrada en actividades. Los aportes recientes pueden ser provisionales; la confirmación para finalizar necesita al menos 48 horas y una nueva lectura de Salud.'],
  ['Medallas y envíos', 'El avance en la app y el envío físico se gestionan por separado. La modalidad, disponibilidad, requisitos y plazos de tu pedido determinan cuándo se despacha la medalla. Revisá tu dirección y las condiciones de envío de tu país en korva.run. No todas las rutas incluyen productos físicos.'],
  ['Compras y consultas', 'Las solicitudes sobre acceso, cobros, cancelaciones, devoluciones o productos dañados se gestionan por escrito con soporte y según las condiciones del pedido y la normativa aplicable. Estos términos no eliminan derechos obligatorios del consumidor.'],
  ['Actividad responsable', 'Elegí una actividad y una intensidad adecuadas para vos y detenete si sentís malestar. Korva no ofrece diagnóstico, tratamiento ni asesoramiento médico y no garantiza resultados deportivos. El GPS y los mapas pueden tener errores; priorizá las condiciones reales y tu seguridad.'],
  ['Tu cuenta y el contenido', 'Protegé tus credenciales y registrá información veraz. No uses la app para fraude, acoso o acceso no autorizado. Korva puede investigar registros inconsistentes y restringir usos abusivos. Podés solicitar ayuda o eliminar tu cuenta desde Perfil. El contenido de la app pertenece a Korva o a sus respectivos titulares.'],
  ['Contacto y actualizaciones', 'Escribinos a korvaventura@gmail.com. Podremos actualizar estos términos y mostrar la nueva versión cuando corresponda. Los permisos de Salud, ubicación y notificaciones se gestionan aparte; aceptar estos términos no los activa.'],
];
export const PRIVACIDAD = [
  ['Quién trata tus datos', 'Korva Adventures LLC opera Korva Aventuras. Contacto para privacidad, acceso, corrección o eliminación: korvaventura@gmail.com. Esta política describe los datos de la app; la tienda tiene además su política de privacidad publicada en korva.run.'],
  ['Cuenta, pedidos y actividad', 'Tratamos datos de cuenta y perfil, como nombre, correo y foto si la agregás; datos necesarios para pedidos y envíos; actividades registradas, distancias, fechas, deporte, progreso, pausas y preferencias. Usamos estos datos para identificar tu cuenta, prestar el servicio, gestionar pedidos, dar soporte y mantener la seguridad.'],
  ['Ubicación durante el GPS', 'Cuando iniciás una actividad GPS y otorgás permiso, la app usa tu ubicación para medir y registrar el recorrido. Durante esa actividad puede seguir registrando al bloquear el teléfono o usar otra app si autorizás el permiso correspondiente. Los recorridos guardados se asocian a tu actividad y cuenta. Podés detener la actividad y revocar el permiso en los ajustes del teléfono.'],
  ['Apple Salud y Health Connect', 'Solo si elegís conectar Salud, Korva consulta pasos y distancia de caminata, carrera y bicicleta. En Android también consulta sesiones de ejercicio para identificar y organizar esas distancias. Se sincronizan con el servidor de Korva resúmenes diarios, fechas, zona horaria e información de fuente o dispositivo cuando está disponible, asociados a tu cuenta. No convertimos pasos a kilómetros y esta versión no escribe ni modifica datos en Salud.'],
  ['Para qué usamos Salud', 'Usamos esos datos para mostrar tu movimiento y, únicamente en los desafíos que confirmes, calcular aportes de distancia sin duplicar actividades. No usamos datos de Salud para publicidad, marketing ni venta de datos. No compartimos esos datos con la tienda, transportistas o redes sociales para esos fines. Los proveedores técnicos que sostienen el servicio procesan lo necesario para estas funciones.'],
  ['Tus controles de Salud', 'Podés usar Korva sin conectar Salud. Conectarla no activa aportes a desafíos. Podés desactivar los aportes por desafío, desconectar la sincronización en Tu movimiento y revocar permisos en Apple Salud o Health Connect. Desconectar no borra automáticamente los resúmenes ni el progreso ya registrado; podés solicitar su eliminación o eliminar tu cuenta.'],
  ['Strava y otros permisos', 'Strava se conecta solo si lo autorizás; tratamos datos y credenciales de esa conexión para importar actividades. Podés desconectarlo desde Perfil. La foto de perfil requiere tu elección y los permisos necesarios. Las notificaciones son opcionales; el permiso se puede cambiar en los ajustes del teléfono.'],
  ['Infraestructura y proveedores', 'Utilizamos Supabase para cuenta y datos, Railway para el backend y proveedores de comunicaciones, como Expo y Resend. La tienda y los pedidos pueden involucrar Shopify, procesadores de pago y transportistas. Cada uno recibe los datos necesarios para su función. También podremos responder a obligaciones legales. El procesamiento puede ocurrir fuera de tu país.'],
  ['Compartir y comunidad', 'Al compartir una imagen de progreso o actividad, vos elegís la aplicación destinataria. Revisá la imagen: puede contener nombre, kilómetros y, en actividades, tu recorrido. Esa aplicación aplica sus propias condiciones. Las funciones de comunidad pueden mostrar el perfil y progreso que formen parte de ellas; evitá incluir datos sensibles en tu nombre o foto.'],
  ['Conservación, seguridad y eliminación', 'Conservamos los datos necesarios para operar tu cuenta y prestar el servicio. Podés eliminar tu cuenta desde Perfil o contactarnos para ejercer tus derechos según tu lugar de residencia. Ciertos registros de pedidos, obligaciones legales o prevención de fraude pueden requerir conservación; algunos historiales pueden quedar anonimizados. Aplicamos medidas de seguridad, pero ningún sistema garantiza protección absoluta.'],
  ['Menores y cambios', 'El servicio no está destinado a menores de edad. Si detectás una cuenta de un menor, contactanos. Cuando actualicemos esta política indicaremos la fecha y mostraremos los cambios relevantes en la app.'],
];
