// Offline calibration for this generated asset. Does not alter challenge coordinates.
const fs=require('node:fs');const path=require('node:path');const {decodificarModelo}=require('../services/mapa3d/modeloMeshyCore');
const root=path.resolve(__dirname,'../assets/mapa3d/dubrovnik-completo');const meta=require(root+'/meta');const mesh=decodificarModelo(meta,Object.fromEntries(['position','normal','uv','index'].map(k=>[k,require(root+'/'+k)])));const s=mesh.position,idx=mesh.index,cell=.075,cells=new Map();
for(let i=0;i<idx.length;i+=3){const a=idx[i]*3,b=idx[i+1]*3,c=idx[i+2]*3;const minX=Math.floor(Math.min(s[a],s[b],s[c])/cell),maxX=Math.floor(Math.max(s[a],s[b],s[c])/cell),minZ=Math.floor(Math.min(s[a+2],s[b+2],s[c+2])/cell),maxZ=Math.floor(Math.max(s[a+2],s[b+2],s[c+2])/cell);for(let x=minX;x<=maxX;x++)for(let z=minZ;z<=maxZ;z++){const key=x+','+z;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(i);}}
function at(x,z){let h=0;for(const i of cells.get(Math.floor(x/cell)+','+Math.floor(z/cell))||[]){const a=idx[i]*3,b=idx[i+1]*3,c=idx[i+2]*3;const den=(s[b+2]-s[c+2])*(s[a]-s[c])+(s[c]-s[b])*(s[a+2]-s[c+2]);if(Math.abs(den)<1e-10)continue;const u=((s[b+2]-s[c+2])*(x-s[c])+(s[c]-s[b])*(z-s[c+2]))/den,v=((s[c+2]-s[a+2])*(x-s[c])+(s[a]-s[c])*(z-s[c+2]))/den;if(u>=-1e-6&&v>=-1e-6&&u+v<=1+1e-6)h=Math.max(h,u*s[a+1]+v*s[b+1]+(1-u-v)*s[c+1]);}return h;}
const pixels=[[835,648,0],[860,690],[880,740],[900,800,4],[880,740],[860,690],[835,648],[890,672],[950,691,8],[1005,715],[1070,738,12],[1107,700],[1125,650],[1110,705],[1060,740],[980,720],[900,665],[855,600],[845,520],[880,460],[920,410],[990,340,16],[950,400],[930,470],[920,520],[910,580],[950,625,19.4]];
const knots=pixels.map(([x,z,km])=>({x:(z/699.5-1)*3,z:-(x/699.5-1)*3,km}));const distances=[0];for(let i=1;i<knots.length;i++)distances[i]=distances[i-1]+Math.hypot(knots[i].x-knots[i-1].x,knots[i].z-knots[i-1].z);let start=0;for(let end=1;end<knots.length;end++)if(Number.isFinite(knots[end].km)){for(let i=start+1;i<end;i++)knots[i].km=knots[start].km+(knots[end].km-knots[start].km)*(distances[i]-distances[start])/(distances[end]-distances[start]);start=end;}
const route=[];for(let i=1;i<knots.length;i++){const a=knots[i-1],b=knots[i],n=Math.max(1,Math.ceil(Math.hypot(a.x-b.x,a.z-b.z)/.008));for(let j=i===1?0:1;j<=n;j++){const t=j/n,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;route.push({x:x*.3,z:z*.3,km:a.km+(b.km-a.km)*t,h:at(x,z)/.004});}}
meta.visualRoute=knots.filter(p=>[0,4,8,12,16,19.4].includes(p.km)).map(p=>[p.x,p.z,p.km]);meta.visualSurfaceRoute=route;fs.writeFileSync(root+'/meta.js','module.exports = '+JSON.stringify(meta)+';\n');console.log({samples:route.length,minHeight:Math.min(...route.map(p=>p.h*.004)),maxHeight:Math.max(...route.map(p=>p.h*.004))});
