const fs=require('node:fs'),path=require('node:path');const input=process.argv[2];if(!input)throw Error('Pass preview-assets.json');const assets=JSON.parse(fs.readFileSync(input,'utf8'));const root=path.resolve(__dirname,'../assets/mapa3d');const b64=a=>Buffer.from(a.buffer,a.byteOffset,a.byteLength).toString('base64');const decode=(s,T)=>{const b=Buffer.from(s,'base64');return new T(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength));};
const meshes=assets.map(a=>({kind:a.kind,pos:decode(a.position,Float32Array),normal:decode(a.normal,Float32Array),uv:decode(a.uv,Float32Array),idx:decode(a.index,Uint32Array),texture:a.texture}));
const bg=meshes.find(m=>m.kind==='background');
const smooth=t=>t*t*(3-2*t);
for(let i=0;i<bg.pos.length;i+=3){
 const x=Math.abs(bg.pos[i]),z=bg.pos[i+2],original=bg.pos[i+1]*.85;
 const ramp=smooth(Math.max(0,Math.min(1,(.85-z)/2.5)));
 const cap=.03+.85*ramp;
 const lateral=smooth(Math.max(0,Math.min(1,(3.3-x)/1.3)));
 let y=original+(Math.min(original,cap)-original)*lateral;
 const hole=smooth(Math.max(0,Math.min(1,(1.82-x)/.3)))*smooth(Math.max(0,Math.min(1,(z-.92)/.3)));
 const front=smooth(Math.max(0,Math.min(1,(z-1.35)/.85)));
 const mask=1-(1-hole)*(1-front);
 bg.pos[i+1]=y*(1-mask)-.04*mask;
}
for(const m of meshes){const folder=m.kind==='city'?'dubrovnik-completo':'dubrovnik-revision-fondo';const out=path.join(root,folder);fs.mkdirSync(out,{recursive:true});let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<m.pos.length;i++) {const k=i%3;min[k]=Math.min(min[k],m.pos[i]);max[k]=Math.max(max[k],m.pos[i]);}const span=max.map((v,k)=>v-min[k]),p=new Uint16Array(m.pos.length),n=new Int8Array(m.normal.length),uv=new Uint16Array(m.uv.length);for(let i=0;i<p.length;i++)p[i]=Math.round((m.pos[i]-min[i%3])/span[i%3]*65535);for(let i=0;i<n.length;i+=3){const len=Math.hypot(...m.normal.subarray(i,i+3))||1;for(let k=0;k<3;k++)n[i+k]=Math.round(m.normal[i+k]/len*127);}for(let i=0;i<uv.length;i++)uv[i]=Math.round(Math.min(1,Math.max(0,m.uv[i]))*65535);let prev=0;const bytes=[];for(const v of m.idx){let delta=v-prev;prev=v;let q=delta<0?-delta*2-1:delta*2;while(q>=128){bytes.push(q%128|128);q=Math.floor(q/128);}bytes.push(q);}
for(const [name,a]of [['position',p],['normal',n],['uv',uv],['index',Uint8Array.from(bytes)]])fs.writeFileSync(path.join(out,name+'.js'),'module.exports = '+JSON.stringify(b64(a))+';\n');fs.writeFileSync(path.join(out,'color.jpg'),Buffer.from(m.texture.split(',')[1],'base64'));m.meta={version:1,vertices:m.pos.length/3,triangles:m.idx.length/3,min,span};m.folder=folder;}
// Rasterize both surfaces for collision clearance, separate from the exact route.
const min=[Math.min(...meshes.map(m=>m.meta.min[0])),Math.min(...meshes.map(m=>m.meta.min[2]))],max=[Math.max(...meshes.map(m=>m.meta.min[0]+m.meta.span[0])),Math.max(...meshes.map(m=>m.meta.min[2]+m.meta.span[2]))],size=192,h=new Float32Array(size*size);const gx=x=>(x-min[0])/(max[0]-min[0])*(size-1),gz=z=>(z-min[1])/(max[1]-min[1])*(size-1);
for(const m of meshes)for(let i=0;i<m.idx.length;i+=3){const ids=[m.idx[i],m.idx[i+1],m.idx[i+2]],xs=ids.map(v=>gx(m.pos[v*3])),zs=ids.map(v=>gz(m.pos[v*3+2])),y=Math.max(0,...ids.map(v=>m.pos[v*3+1]));for(let z=Math.max(0,Math.floor(Math.min(...zs)));z<=Math.min(size-1,Math.ceil(Math.max(...zs)));z++)for(let x=Math.max(0,Math.floor(Math.min(...xs)));x<=Math.min(size-1,Math.ceil(Math.max(...xs)));x++)h[z*size+x]=Math.max(h[z*size+x],y);}
const qh=new Uint16Array(h.length);for(let z=0;z<size;z++)for(let x=0;x<size;x++){let v=0;for(let dz=-1;dz<=1;dz++)for(let dx=-1;dx<=1;dx++)if(z+dz>=0&&z+dz<size&&x+dx>=0&&x+dx<size)v=Math.max(v,h[(z+dz)*size+x+dx]);if(v>=1)throw Error('Height overflow');qh[z*size+x]=Math.round(v*65535);}
const city=meshes.find(m=>m.kind==='city'),s=city.pos,idx=city.idx,cell=.05,cells=new Map();for(let i=0;i<idx.length;i+=3){const a=idx[i]*3,b=idx[i+1]*3,c=idx[i+2]*3;for(let x=Math.floor(Math.min(s[a],s[b],s[c])/cell);x<=Math.floor(Math.max(s[a],s[b],s[c])/cell);x++)for(let z=Math.floor(Math.min(s[a+2],s[b+2],s[c+2])/cell);z<=Math.floor(Math.max(s[a+2],s[b+2],s[c+2])/cell);z++){const key=x+','+z;if(!cells.has(key))cells.set(key,[]);cells.get(key).push(i);}}
function at(x,z){let y=0;for(const i of cells.get(Math.floor(x/cell)+','+Math.floor(z/cell))||[]){const a=idx[i]*3,b=idx[i+1]*3,c=idx[i+2]*3,den=(s[b+2]-s[c+2])*(s[a]-s[c])+(s[c]-s[b])*(s[a+2]-s[c+2]);if(Math.abs(den)<1e-10)continue;const u=((s[b+2]-s[c+2])*(x-s[c])+(s[c]-s[b])*(z-s[c+2]))/den,v=((s[c+2]-s[a+2])*(x-s[c])+(s[a]-s[c])*(z-s[c+2]))/den;if(u>=0&&v>=0&&u+v<=1)y=Math.max(y,u*s[a+1]+v*s[b+1]+(1-u-v)*s[c+1]);}return y;}
const pixels=[[135,132,0],[115,210],[108,280],[112,340,4],[108,280],[115,210],[135,132],[210,140],[305,132],[315,235,8],[305,132],[210,140],[135,132],[115,210],[118,320],[151,416],[168,440,12],[151,416],[118,320],[115,210],[135,132],[165,90],[180,62],[175,45],[290,43],[400,46],[465,55,16],[485,110],[468,180],[455,245],[480,320],[521,385],[543,435],[568,430],[545,320],[514,210,19.4]];
const knots=pixels.map(([x,z,km])=>({x:(x/324.5-1)*1.7,z:(z/324.5-1)*1.7+2.45,km}));const ds=[0];for(let i=1;i<knots.length;i++)ds[i]=ds[i-1]+Math.hypot(knots[i].x-knots[i-1].x,knots[i].z-knots[i-1].z);let from=0;for(let to=1;to<knots.length;to++)if(Number.isFinite(knots[to].km)){for(let i=from+1;i<to;i++)knots[i].km=knots[from].km+(knots[to].km-knots[from].km)*(ds[i]-ds[from])/(ds[to]-ds[from]);from=to;}
const route=[];for(let i=1;i<knots.length;i++){const a=knots[i-1],b=knots[i],steps=Math.ceil(Math.hypot(a.x-b.x,a.z-b.z)/.008);for(let j=i===1?0:1;j<=steps;j++){const t=j/steps,x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;route.push({x:x*.3,z:z*.3,h:at(x,z)/.004,km:a.km+(b.km-a.km)*t});}}
city.meta={...city.meta,heightSize:size,heightBounds:[min,max],height:b64(qh),visualRoute:pixels.filter(p=>Number.isFinite(p[2])).map(([x,z,km])=>[(x/324.5-1)*1.7,(z/324.5-1)*1.7+2.45,km]),visualSurfaceRoute:route,composition:'original-old-town + separately masked background'};
for(const m of meshes)fs.writeFileSync(path.join(root,m.folder,'meta.js'),'module.exports = '+JSON.stringify(m.meta)+';\n');console.log(meshes.map(m=>({kind:m.kind,triangles:m.meta.triangles})),{route:route.length,low:route.filter(p=>p.h*.004<.005).length});
